/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './develop/__root'
import { Route as ClerkRouteRouteImport } from './develop/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './develop/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './develop/_authenticated/index'
import { Route as errors503RouteImport } from './develop/(errors)/503'
import { Route as errors500RouteImport } from './develop/(errors)/500'
import { Route as errors404RouteImport } from './develop/(errors)/404'
import { Route as errors403RouteImport } from './develop/(errors)/403'
import { Route as errors401RouteImport } from './develop/(errors)/401'
import { Route as authSignUpRouteImport } from './develop/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './develop/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './develop/(auth)/sign-in'
import { Route as authOtpRouteImport } from './develop/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './develop/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './develop/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './develop/clerk/(auth)/route'
import { Route as AuthenticatedDemosIndexRouteImport } from './develop/_authenticated/demos/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './develop/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './develop/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './develop/clerk/(auth)/sign-in'
import { Route as AuthenticatedOfficialSettingsRouteRouteImport } from './develop/_authenticated/official/settings/route'
import { Route as AuthenticatedOfficialUsersIndexRouteImport } from './develop/_authenticated/official/users/index'
import { Route as AuthenticatedOfficialTasksIndexRouteImport } from './develop/_authenticated/official/tasks/index'
import { Route as AuthenticatedOfficialSettingsIndexRouteImport } from './develop/_authenticated/official/settings/index'
import { Route as AuthenticatedOfficialHelpCenterIndexRouteImport } from './develop/_authenticated/official/help-center/index'
import { Route as AuthenticatedOfficialChatsIndexRouteImport } from './develop/_authenticated/official/chats/index'
import { Route as AuthenticatedOfficialAppsIndexRouteImport } from './develop/_authenticated/official/apps/index'
import { Route as AuthenticatedDemosDemo2IndexRouteImport } from './develop/_authenticated/demos/demo2/index'
import { Route as AuthenticatedDemosDemo1IndexRouteImport } from './develop/_authenticated/demos/demo1/index'
import { Route as AuthenticatedOfficialSettingsNotificationsRouteImport } from './develop/_authenticated/official/settings/notifications'
import { Route as AuthenticatedOfficialSettingsDisplayRouteImport } from './develop/_authenticated/official/settings/display'
import { Route as AuthenticatedOfficialSettingsAppearanceRouteImport } from './develop/_authenticated/official/settings/appearance'
import { Route as AuthenticatedOfficialSettingsAccountRouteImport } from './develop/_authenticated/official/settings/account'
import { Route as AuthenticatedOfficialErrorsErrorRouteImport } from './develop/_authenticated/official/errors/$error'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedDemosIndexRoute = AuthenticatedDemosIndexRouteImport.update({
  id: '/demos/',
  path: '/demos/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedOfficialSettingsRouteRoute =
  AuthenticatedOfficialSettingsRouteRouteImport.update({
    id: '/official/settings',
    path: '/official/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficialUsersIndexRoute =
  AuthenticatedOfficialUsersIndexRouteImport.update({
    id: '/official/users/',
    path: '/official/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficialTasksIndexRoute =
  AuthenticatedOfficialTasksIndexRouteImport.update({
    id: '/official/tasks/',
    path: '/official/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficialSettingsIndexRoute =
  AuthenticatedOfficialSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOfficialSettingsRouteRoute,
  } as any)
const AuthenticatedOfficialHelpCenterIndexRoute =
  AuthenticatedOfficialHelpCenterIndexRouteImport.update({
    id: '/official/help-center/',
    path: '/official/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficialChatsIndexRoute =
  AuthenticatedOfficialChatsIndexRouteImport.update({
    id: '/official/chats/',
    path: '/official/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficialAppsIndexRoute =
  AuthenticatedOfficialAppsIndexRouteImport.update({
    id: '/official/apps/',
    path: '/official/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemosDemo2IndexRoute =
  AuthenticatedDemosDemo2IndexRouteImport.update({
    id: '/demos/demo2/',
    path: '/demos/demo2/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemosDemo1IndexRoute =
  AuthenticatedDemosDemo1IndexRouteImport.update({
    id: '/demos/demo1/',
    path: '/demos/demo1/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficialSettingsNotificationsRoute =
  AuthenticatedOfficialSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedOfficialSettingsRouteRoute,
  } as any)
const AuthenticatedOfficialSettingsDisplayRoute =
  AuthenticatedOfficialSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedOfficialSettingsRouteRoute,
  } as any)
const AuthenticatedOfficialSettingsAppearanceRoute =
  AuthenticatedOfficialSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedOfficialSettingsRouteRoute,
  } as any)
const AuthenticatedOfficialSettingsAccountRoute =
  AuthenticatedOfficialSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedOfficialSettingsRouteRoute,
  } as any)
const AuthenticatedOfficialErrorsErrorRoute =
  AuthenticatedOfficialErrorsErrorRouteImport.update({
    id: '/official/errors/$error',
    path: '/official/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/official/settings': typeof AuthenticatedOfficialSettingsRouteRouteWithChildren
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/demos': typeof AuthenticatedDemosIndexRoute
  '/official/errors/$error': typeof AuthenticatedOfficialErrorsErrorRoute
  '/official/settings/account': typeof AuthenticatedOfficialSettingsAccountRoute
  '/official/settings/appearance': typeof AuthenticatedOfficialSettingsAppearanceRoute
  '/official/settings/display': typeof AuthenticatedOfficialSettingsDisplayRoute
  '/official/settings/notifications': typeof AuthenticatedOfficialSettingsNotificationsRoute
  '/demos/demo1': typeof AuthenticatedDemosDemo1IndexRoute
  '/demos/demo2': typeof AuthenticatedDemosDemo2IndexRoute
  '/official/apps': typeof AuthenticatedOfficialAppsIndexRoute
  '/official/chats': typeof AuthenticatedOfficialChatsIndexRoute
  '/official/help-center': typeof AuthenticatedOfficialHelpCenterIndexRoute
  '/official/settings/': typeof AuthenticatedOfficialSettingsIndexRoute
  '/official/tasks': typeof AuthenticatedOfficialTasksIndexRoute
  '/official/users': typeof AuthenticatedOfficialUsersIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/demos': typeof AuthenticatedDemosIndexRoute
  '/official/errors/$error': typeof AuthenticatedOfficialErrorsErrorRoute
  '/official/settings/account': typeof AuthenticatedOfficialSettingsAccountRoute
  '/official/settings/appearance': typeof AuthenticatedOfficialSettingsAppearanceRoute
  '/official/settings/display': typeof AuthenticatedOfficialSettingsDisplayRoute
  '/official/settings/notifications': typeof AuthenticatedOfficialSettingsNotificationsRoute
  '/demos/demo1': typeof AuthenticatedDemosDemo1IndexRoute
  '/demos/demo2': typeof AuthenticatedDemosDemo2IndexRoute
  '/official/apps': typeof AuthenticatedOfficialAppsIndexRoute
  '/official/chats': typeof AuthenticatedOfficialChatsIndexRoute
  '/official/help-center': typeof AuthenticatedOfficialHelpCenterIndexRoute
  '/official/settings': typeof AuthenticatedOfficialSettingsIndexRoute
  '/official/tasks': typeof AuthenticatedOfficialTasksIndexRoute
  '/official/users': typeof AuthenticatedOfficialUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/official/settings': typeof AuthenticatedOfficialSettingsRouteRouteWithChildren
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/demos/': typeof AuthenticatedDemosIndexRoute
  '/_authenticated/official/errors/$error': typeof AuthenticatedOfficialErrorsErrorRoute
  '/_authenticated/official/settings/account': typeof AuthenticatedOfficialSettingsAccountRoute
  '/_authenticated/official/settings/appearance': typeof AuthenticatedOfficialSettingsAppearanceRoute
  '/_authenticated/official/settings/display': typeof AuthenticatedOfficialSettingsDisplayRoute
  '/_authenticated/official/settings/notifications': typeof AuthenticatedOfficialSettingsNotificationsRoute
  '/_authenticated/demos/demo1/': typeof AuthenticatedDemosDemo1IndexRoute
  '/_authenticated/demos/demo2/': typeof AuthenticatedDemosDemo2IndexRoute
  '/_authenticated/official/apps/': typeof AuthenticatedOfficialAppsIndexRoute
  '/_authenticated/official/chats/': typeof AuthenticatedOfficialChatsIndexRoute
  '/_authenticated/official/help-center/': typeof AuthenticatedOfficialHelpCenterIndexRoute
  '/_authenticated/official/settings/': typeof AuthenticatedOfficialSettingsIndexRoute
  '/_authenticated/official/tasks/': typeof AuthenticatedOfficialTasksIndexRoute
  '/_authenticated/official/users/': typeof AuthenticatedOfficialUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/official/settings'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/demos'
    | '/official/errors/$error'
    | '/official/settings/account'
    | '/official/settings/appearance'
    | '/official/settings/display'
    | '/official/settings/notifications'
    | '/demos/demo1'
    | '/demos/demo2'
    | '/official/apps'
    | '/official/chats'
    | '/official/help-center'
    | '/official/settings/'
    | '/official/tasks'
    | '/official/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/demos'
    | '/official/errors/$error'
    | '/official/settings/account'
    | '/official/settings/appearance'
    | '/official/settings/display'
    | '/official/settings/notifications'
    | '/demos/demo1'
    | '/demos/demo2'
    | '/official/apps'
    | '/official/chats'
    | '/official/help-center'
    | '/official/settings'
    | '/official/tasks'
    | '/official/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/official/settings'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/demos/'
    | '/_authenticated/official/errors/$error'
    | '/_authenticated/official/settings/account'
    | '/_authenticated/official/settings/appearance'
    | '/_authenticated/official/settings/display'
    | '/_authenticated/official/settings/notifications'
    | '/_authenticated/demos/demo1/'
    | '/_authenticated/demos/demo2/'
    | '/_authenticated/official/apps/'
    | '/_authenticated/official/chats/'
    | '/_authenticated/official/help-center/'
    | '/_authenticated/official/settings/'
    | '/_authenticated/official/tasks/'
    | '/_authenticated/official/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/demos/': {
      id: '/_authenticated/demos/'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof AuthenticatedDemosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/official/settings': {
      id: '/_authenticated/official/settings'
      path: '/official/settings'
      fullPath: '/official/settings'
      preLoaderRoute: typeof AuthenticatedOfficialSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/official/users/': {
      id: '/_authenticated/official/users/'
      path: '/official/users'
      fullPath: '/official/users'
      preLoaderRoute: typeof AuthenticatedOfficialUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/official/tasks/': {
      id: '/_authenticated/official/tasks/'
      path: '/official/tasks'
      fullPath: '/official/tasks'
      preLoaderRoute: typeof AuthenticatedOfficialTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/official/settings/': {
      id: '/_authenticated/official/settings/'
      path: '/'
      fullPath: '/official/settings/'
      preLoaderRoute: typeof AuthenticatedOfficialSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedOfficialSettingsRouteRoute
    }
    '/_authenticated/official/help-center/': {
      id: '/_authenticated/official/help-center/'
      path: '/official/help-center'
      fullPath: '/official/help-center'
      preLoaderRoute: typeof AuthenticatedOfficialHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/official/chats/': {
      id: '/_authenticated/official/chats/'
      path: '/official/chats'
      fullPath: '/official/chats'
      preLoaderRoute: typeof AuthenticatedOfficialChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/official/apps/': {
      id: '/_authenticated/official/apps/'
      path: '/official/apps'
      fullPath: '/official/apps'
      preLoaderRoute: typeof AuthenticatedOfficialAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demos/demo2/': {
      id: '/_authenticated/demos/demo2/'
      path: '/demos/demo2'
      fullPath: '/demos/demo2'
      preLoaderRoute: typeof AuthenticatedDemosDemo2IndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demos/demo1/': {
      id: '/_authenticated/demos/demo1/'
      path: '/demos/demo1'
      fullPath: '/demos/demo1'
      preLoaderRoute: typeof AuthenticatedDemosDemo1IndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/official/settings/notifications': {
      id: '/_authenticated/official/settings/notifications'
      path: '/notifications'
      fullPath: '/official/settings/notifications'
      preLoaderRoute: typeof AuthenticatedOfficialSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedOfficialSettingsRouteRoute
    }
    '/_authenticated/official/settings/display': {
      id: '/_authenticated/official/settings/display'
      path: '/display'
      fullPath: '/official/settings/display'
      preLoaderRoute: typeof AuthenticatedOfficialSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedOfficialSettingsRouteRoute
    }
    '/_authenticated/official/settings/appearance': {
      id: '/_authenticated/official/settings/appearance'
      path: '/appearance'
      fullPath: '/official/settings/appearance'
      preLoaderRoute: typeof AuthenticatedOfficialSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedOfficialSettingsRouteRoute
    }
    '/_authenticated/official/settings/account': {
      id: '/_authenticated/official/settings/account'
      path: '/account'
      fullPath: '/official/settings/account'
      preLoaderRoute: typeof AuthenticatedOfficialSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedOfficialSettingsRouteRoute
    }
    '/_authenticated/official/errors/$error': {
      id: '/_authenticated/official/errors/$error'
      path: '/official/errors/$error'
      fullPath: '/official/errors/$error'
      preLoaderRoute: typeof AuthenticatedOfficialErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedOfficialSettingsRouteRouteChildren {
  AuthenticatedOfficialSettingsAccountRoute: typeof AuthenticatedOfficialSettingsAccountRoute
  AuthenticatedOfficialSettingsAppearanceRoute: typeof AuthenticatedOfficialSettingsAppearanceRoute
  AuthenticatedOfficialSettingsDisplayRoute: typeof AuthenticatedOfficialSettingsDisplayRoute
  AuthenticatedOfficialSettingsNotificationsRoute: typeof AuthenticatedOfficialSettingsNotificationsRoute
  AuthenticatedOfficialSettingsIndexRoute: typeof AuthenticatedOfficialSettingsIndexRoute
}

const AuthenticatedOfficialSettingsRouteRouteChildren: AuthenticatedOfficialSettingsRouteRouteChildren =
  {
    AuthenticatedOfficialSettingsAccountRoute:
      AuthenticatedOfficialSettingsAccountRoute,
    AuthenticatedOfficialSettingsAppearanceRoute:
      AuthenticatedOfficialSettingsAppearanceRoute,
    AuthenticatedOfficialSettingsDisplayRoute:
      AuthenticatedOfficialSettingsDisplayRoute,
    AuthenticatedOfficialSettingsNotificationsRoute:
      AuthenticatedOfficialSettingsNotificationsRoute,
    AuthenticatedOfficialSettingsIndexRoute:
      AuthenticatedOfficialSettingsIndexRoute,
  }

const AuthenticatedOfficialSettingsRouteRouteWithChildren =
  AuthenticatedOfficialSettingsRouteRoute._addFileChildren(
    AuthenticatedOfficialSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOfficialSettingsRouteRoute: typeof AuthenticatedOfficialSettingsRouteRouteWithChildren
  AuthenticatedDemosIndexRoute: typeof AuthenticatedDemosIndexRoute
  AuthenticatedOfficialErrorsErrorRoute: typeof AuthenticatedOfficialErrorsErrorRoute
  AuthenticatedDemosDemo1IndexRoute: typeof AuthenticatedDemosDemo1IndexRoute
  AuthenticatedDemosDemo2IndexRoute: typeof AuthenticatedDemosDemo2IndexRoute
  AuthenticatedOfficialAppsIndexRoute: typeof AuthenticatedOfficialAppsIndexRoute
  AuthenticatedOfficialChatsIndexRoute: typeof AuthenticatedOfficialChatsIndexRoute
  AuthenticatedOfficialHelpCenterIndexRoute: typeof AuthenticatedOfficialHelpCenterIndexRoute
  AuthenticatedOfficialTasksIndexRoute: typeof AuthenticatedOfficialTasksIndexRoute
  AuthenticatedOfficialUsersIndexRoute: typeof AuthenticatedOfficialUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOfficialSettingsRouteRoute:
    AuthenticatedOfficialSettingsRouteRouteWithChildren,
  AuthenticatedDemosIndexRoute: AuthenticatedDemosIndexRoute,
  AuthenticatedOfficialErrorsErrorRoute: AuthenticatedOfficialErrorsErrorRoute,
  AuthenticatedDemosDemo1IndexRoute: AuthenticatedDemosDemo1IndexRoute,
  AuthenticatedDemosDemo2IndexRoute: AuthenticatedDemosDemo2IndexRoute,
  AuthenticatedOfficialAppsIndexRoute: AuthenticatedOfficialAppsIndexRoute,
  AuthenticatedOfficialChatsIndexRoute: AuthenticatedOfficialChatsIndexRoute,
  AuthenticatedOfficialHelpCenterIndexRoute:
    AuthenticatedOfficialHelpCenterIndexRoute,
  AuthenticatedOfficialTasksIndexRoute: AuthenticatedOfficialTasksIndexRoute,
  AuthenticatedOfficialUsersIndexRoute: AuthenticatedOfficialUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
